"""Citation review refuses false provenance even when an answer sounds correct."""

import copy
import hashlib
import importlib
import importlib.util
import json
import unittest

ARTIFACT = "or1_" + "a" * 64
EVIDENCE = "p0003-b0001-s0000"


def fixture():
    passage = dict(
        evidence_id=EVIDENCE,
        page=3,
        text_origin="native",
        text="Provide 60 days notice.",
        block_index=1,
        segment_index=0,
        source_kind="block_text",
        text_start=0,
        text_end=23,
    )
    read = dict(
        schema_version="0.3",
        artifact_id=ARTIFACT,
        display_name="agreement.pdf",
        passages=[passage],
        next_cursor=None,
    )

    def call(identifier, name, arguments, result):
        return [
            dict(kind="request", id=identifier, name=name, arguments=arguments),
            dict(
                kind="response",
                id=identifier,
                result=dict(isError=False, content=[dict(type="text", text=json.dumps(result))]),
            ),
        ]

    events = call(
        "i",
        "mcp__proof__openreading_import",
        {"path": "agreement.pdf"},
        dict(
            schema_version="0.3",
            artifact_id=ARTIFACT,
            display_name="agreement.pdf",
            document_sha256="b" * 64,
            page_count=24,
            passage_count=30,
            reused=False,
            warnings=[],
        ),
    )
    events += call(
        "s",
        "mcp__proof__openreading_search",
        {"artifact_id": ARTIFACT, "query": "notice"},
        dict(
            schema_version="0.3",
            artifact_id=ARTIFACT,
            query="notice",
            hits=[
                dict(
                    evidence_id=EVIDENCE,
                    page=3,
                    text_origin="native",
                    matched_terms=["notice"],
                    excerpt_start=0,
                    excerpt_end=23,
                    excerpt=passage["text"],
                )
            ],
        ),
    )
    events += call(
        "r",
        "mcp__proof__openreading_read",
        {"artifact_id": ARTIFACT, "evidence_ids": [EVIDENCE]},
        read,
    )
    answer = "Provide 60 days notice. Source: agreement.pdf, physical PDF page 3."
    events.append(dict(kind="answer", text=answer))
    capture = dict(
        format_version=1,
        host=dict(application="Synthetic host", version="1", mode="fixture"),
        complete=True,
        tools={verb: f"mcp__proof__openreading_{verb}" for verb in ("import", "search", "read")},
        events=events,
    )
    citation = dict(
        artifact_id=ARTIFACT,
        evidence_id=EVIDENCE,
        page=3,
        text_origin="native",
        import_call="i",
        search_call="s",
        read_call="r",
        quote_span=[0, 23],
        filename_span=[32, 45],
        page_span=[47, 66],
        origin_span=None,
    )
    # Literal spans are checked against the actual rendered text, never generated by the checker.
    review = dict(
        format_version=1,
        capture_sha256=hashlib.sha256(json.dumps(capture).encode()).hexdigest(),
        citations_complete=True,
        citations=[citation],
    )
    return capture, review, read


class CitationTests(unittest.IsolatedAsyncioTestCase):
    def module(self):
        self.assertIsNotNone(
            importlib.util.find_spec("measurement.citations"),
            "Citation verification is not implemented",
        )
        return importlib.import_module("measurement.citations")

    async def check(self, capture, review, retained):
        async def resolve(artifact, evidence):
            if artifact != ARTIFACT or evidence != EVIDENCE:
                raise ValueError("Evidence is absent")
            return copy.deepcopy(retained)

        return await self.module().check(capture, review, resolve)

    async def test_exact_quote_and_physical_page_resolve_through_read(self):
        capture, review, retained = fixture()
        result = await self.check(capture, review, retained)
        self.assertEqual(result["verified_citations"], 1)
        self.assertEqual(result["answer_quality"], "requires_human_review")
        self.assertEqual(result["native_host_support"], "unverified")

    async def test_wrong_page_paraphrase_other_artifact_and_missing_calls_fail(self):
        for fault in (
            "page",
            "quote",
            "artifact",
            "read",
            "search",
            "import",
            "retained",
            "origin",
            "filename",
            "order",
            "missing_trace",
            "unreviewed_inventory",
        ):
            with self.subTest(fault=fault):
                capture, review, retained = fixture()
                c = review["citations"][0]
                if fault == "page":
                    c["page"] = 4
                elif fault == "quote":
                    capture["events"][-1]["text"] = capture["events"][-1]["text"].replace(
                        "Provide", "Deliver"
                    )
                elif fault == "artifact":
                    c["artifact_id"] = "or1_" + "c" * 64
                elif fault in ("read", "search", "import"):
                    c[f"{fault}_call"] = "absent"
                elif fault == "retained":
                    retained["passages"][0]["text"] = "Pay immediately."
                elif fault == "origin":
                    retained["passages"][0]["text_origin"] = "ocr"
                elif fault == "filename":
                    retained["display_name"] = "other.pdf"
                elif fault == "order":
                    capture["events"].insert(4, capture["events"].pop())
                elif fault == "missing_trace":
                    capture["complete"] = False
                else:
                    review["citations_complete"] = False
                with self.assertRaises(ValueError):
                    await self.check(capture, review, retained)

    async def test_ocr_quote_requires_visible_matching_origin_label(self):
        capture, review, retained = fixture()
        retained["passages"][0]["text_origin"] = "ocr"
        capture["events"][5]["result"]["content"][0]["text"] = json.dumps(retained)
        search = json.loads(capture["events"][3]["result"]["content"][0]["text"])
        search["hits"][0]["text_origin"] = "ocr"
        capture["events"][3]["result"]["content"][0]["text"] = json.dumps(search)
        review["citations"][0]["text_origin"] = "ocr"
        with self.assertRaises(ValueError):
            await self.check(capture, review, retained)
        capture["events"][-1]["text"] += " OCR"
        review["citations"][0]["origin_span"] = [68, 71]
        self.assertEqual((await self.check(capture, review, retained))["verified_citations"], 1)

    async def test_malformed_partial_and_ambiguous_capture_is_refused(self):
        mutations = [
            lambda c, r, p: c.update(extra=True),
            lambda c, r, p: c.update(format_version=2),
            lambda c, r, p: c["host"].update(version=""),
            lambda c, r, p: c["tools"].update(read=c["tools"]["search"]),
            lambda c, r, p: c.update(events=[]),
            lambda c, r, p: c["events"][-1].update(text=""),
            lambda c, r, p: c["events"][0].update(id=1),
            lambda c, r, p: c["events"].insert(1, copy.deepcopy(c["events"][0])),
            lambda c, r, p: c["events"].insert(2, copy.deepcopy(c["events"][1])),
            lambda c, r, p: c["events"].pop(5),
            lambda c, r, p: c["events"][0].update(arguments=[]),
            lambda c, r, p: c["events"][4].update(name="ordinary_read"),
            lambda c, r, p: c["events"][4]["arguments"].update(artifact_id="another"),
            lambda c, r, p: c["events"][4]["arguments"].update(evidence_ids=[]),
            lambda c, r, p: c["events"][5]["result"].update(isError=True),
            lambda c, r, p: c["events"][5]["result"].update(content=[]),
            lambda c, r, p: c["events"][5]["result"].update(structuredContent={"different": True}),
            lambda c, r, p: c["events"][5]["result"]["content"][0].update(text="{}"),
            lambda c, r, p: r.update(format_version=True),
            lambda c, r, p: r.update(citations=[]),
            lambda c, r, p: r["citations"][0].update(page=True),
            lambda c, r, p: r["citations"][0].update(text_origin="guessed"),
            lambda c, r, p: r["citations"][0].update(quote_span=[0, 999]),
            lambda c, r, p: r["citations"][0].update(quote_span=[False, 23]),
            lambda c, r, p: r["citations"][0].update(quote_span=None),
            lambda c, r, p: r["citations"].append(copy.deepcopy(r["citations"][0])),
            lambda c, r, p: p.update(artifact_id="other"),
            lambda c, r, p: p.update(passages=[]),
            lambda c, r, p: p["passages"].append(copy.deepcopy(p["passages"][0])),
        ]
        for index, mutate in enumerate(mutations):
            with self.subTest(index=index):
                capture, review, retained = fixture()
                mutate(capture, review, retained)
                with self.assertRaises(ValueError):
                    await self.check(capture, review, retained)

    async def test_capture_cannot_lie_about_the_search_page_or_excerpt(self):
        for changes in (
            {"page": 9},
            {"excerpt": "invented"},
            {"excerpt_end": 999},
            {"evidence_id": "missing"},
        ):
            capture, review, retained = fixture()
            data = json.loads(capture["events"][3]["result"]["content"][0]["text"])
            data["hits"][0].update(changes)
            capture["events"][3]["result"]["content"][0]["text"] = json.dumps(data)
            with self.assertRaises(ValueError):
                await self.check(capture, review, retained)

    async def test_review_binds_exact_capture_bytes(self):
        import tempfile
        from pathlib import Path

        capture, review, retained = fixture()

        async def resolve(*args):
            return retained

        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp).resolve()
            (root / "capture.json").write_text(json.dumps(capture))
            (root / "review.json").write_text(json.dumps(review))
            report = await self.module().check_files(
                root / "capture.json", root / "review.json", resolve
            )
            self.assertEqual(report["capture_sha256"], review["capture_sha256"])
            self.assertEqual(
                report["review_sha256"],
                hashlib.sha256((root / "review.json").read_bytes()).hexdigest(),
            )
            with (root / "capture.json").open("a") as stream:
                stream.write(" ")
            with self.assertRaisesRegex(ValueError, "Capture changed"):
                await self.module().check_files(
                    root / "capture.json", root / "review.json", resolve
                )

    async def test_multiple_quotes_verify_without_conflating_origins(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] += (
            "\nProvide 60 days notice. Source: agreement.pdf, physical PDF page 3."
        )
        extra = copy.deepcopy(review["citations"][0])
        extra["quote_span"] = [68, 91]
        extra["filename_span"] = [100, 113]
        extra["page_span"] = [115, 134]
        review["citations"].append(extra)
        self.assertEqual((await self.check(capture, review, retained))["verified_citations"], 2)

    async def test_page_span_cannot_select_three_from_page_thirty(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] = capture["events"][-1]["text"].replace("page 3.", "page 30.")
        with self.assertRaises(ValueError):
            await self.check(capture, review, retained)

    async def test_filename_annotation_cannot_hide_a_suffix(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] = capture["events"][-1]["text"].replace(
            "agreement.pdf", "agreement.pdfx"
        )
        review["citations"][0]["page_span"] = [48, 67]
        with self.assertRaises(ValueError):
            await self.check(capture, review, retained)

    async def test_page_label_can_end_the_answer(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] = capture["events"][-1]["text"][:-1]
        self.assertEqual((await self.check(capture, review, retained))["verified_citations"], 1)

    async def test_matching_wrong_answer_page_still_disagrees_with_evidence(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] = capture["events"][-1]["text"].replace("page 3", "page 4")
        review["citations"][0]["page"] = 4
        with self.assertRaises(ValueError):
            await self.check(capture, review, retained)

    async def test_same_text_with_changed_retained_offsets_is_refused(self):
        capture, review, retained = fixture()
        retained["passages"][0]["text_start"] = 1
        with self.assertRaises(ValueError):
            await self.check(capture, review, retained)

    async def test_trivial_quotes_are_refused_but_short_values_remain_valid(self):
        for bounds in ([0, 1], [7, 8], [22, 23]):
            with self.subTest(bounds=bounds):
                capture, review, retained = fixture()
                review["citations"][0]["quote_span"] = bounds
                with self.assertRaisesRegex(ValueError, "two letters or digits"):
                    await self.check(capture, review, retained)
        capture, review, retained = fixture()
        review["citations"][0]["quote_span"] = [8, 10]
        # A valid value can lie outside the short search excerpt but inside the read passage.
        result = json.loads(capture["events"][3]["result"]["content"][0]["text"])
        result["hits"][0].update(excerpt="Provide", excerpt_start=0, excerpt_end=7)
        capture["events"][3]["result"]["content"][0]["text"] = json.dumps(result)
        self.assertEqual((await self.check(capture, review, retained))["verified_citations"], 1)

    async def test_repeated_labels_cannot_be_taken_from_an_unrelated_aside(self):
        for separator in ("\n", "\r\n", "\u2028", " "):
            with self.subTest(separator=separator):
                capture, review, retained = fixture()
                answer = (
                    capture["events"][-1]["text"]
                    + separator
                    + "Unrelated aside: agreement.pdf, physical PDF page 3."
                )
                capture["events"][-1]["text"] = answer
                citation = review["citations"][0]
                start = answer.rindex("agreement.pdf")
                citation["filename_span"] = [start, start + 13]
                start = answer.rindex("physical PDF page 3")
                citation["page_span"] = [start, start + 19]
                with self.assertRaisesRegex(ValueError, "follow their quote"):
                    await self.check(capture, review, retained)

    async def test_a_quote_cannot_reuse_labels_before_it(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] += " Another quote: 60 days"
        review["citations"][0]["quote_span"] = [83, 90]
        with self.assertRaisesRegex(ValueError, "follow their quote"):
            await self.check(capture, review, retained)

    async def test_a_quote_cannot_borrow_the_next_quotes_labels(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] = (
            "Provide 60 days notice. Another quote: " + capture["events"][-1]["text"]
        )
        first = review["citations"][0]
        first["filename_span"] = [71, 84]
        first["page_span"] = [86, 105]
        second = copy.deepcopy(first)
        second["quote_span"] = [39, 62]
        review["citations"].append(second)
        with self.assertRaisesRegex(ValueError, "follow their quote"):
            await self.check(capture, review, retained)

    async def test_labels_on_another_line_are_unsupported(self):
        capture, review, retained = fixture()
        capture["events"][-1]["text"] = capture["events"][-1]["text"].replace(
            ". Source:", ".\nSource:"
        )
        with self.assertRaisesRegex(ValueError, "follow their quote"):
            await self.check(capture, review, retained)


class CitationCommandTests(unittest.TestCase):
    def test_cli_reads_through_verified_runtime_and_sanitizes_failure(self):
        import contextlib
        import io
        import tempfile
        from pathlib import Path
        from types import SimpleNamespace as Box
        from unittest.mock import patch

        from measurement import citations

        capture, review, retained = fixture()
        calls = []

        class Session:
            async def __aenter__(self):
                return self

            async def __aexit__(self, *args):
                pass

            async def initialize(self):
                pass

            async def call_tool(self, name, args):
                calls.append((name, args))
                return Box(
                    model_dump=lambda **kw: dict(
                        isError=False, content=[dict(type="text", text=json.dumps(retained))]
                    )
                )

        @contextlib.asynccontextmanager
        async def channel(params):
            self.assertEqual(params.command, str(root / "runtime/openreading-worker"))
            self.assertIn(str(root / "grant ü spaces"), params.args)
            yield None, None

        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp).resolve()
            (root / "capture.json").write_text(json.dumps(capture))
            (root / "review.json").write_text(json.dumps(review))
            argv = [
                "--capture",
                str(root / "capture.json"),
                "--review",
                str(root / "review.json"),
                "--runtime",
                str(root / "runtime"),
                "--input-root",
                str(root / "grant ü spaces"),
                "--client",
                "codex",
            ]
            with (
                patch.object(
                    citations,
                    "verify_release",
                    return_value=dict(
                        format_version="2", core_commit="c" * 40, worker_sha256="d" * 64
                    ),
                ),
                patch.object(citations, "stdio_client", channel),
                patch.object(citations, "ClientSession", return_value=Session()),
                contextlib.redirect_stdout(io.StringIO()) as output,
            ):
                self.assertEqual(citations.main(argv), 0)
            self.assertEqual(json.loads(output.getvalue())["verified_citations"], 1)
            self.assertEqual(
                calls, [("openreading_read", {"artifact_id": ARTIFACT, "evidence_ids": [EVIDENCE]})]
            )
            with (
                patch.object(citations, "verify_release", return_value=dict(format_version="1")),
                contextlib.redirect_stdout(io.StringIO()) as output,
            ):
                self.assertEqual(citations.main(argv), 1)
            self.assertEqual(json.loads(output.getvalue())["citation_evidence"], "refused")
            with (
                patch.object(
                    citations, "verify_release", side_effect=ValueError("PRIVATE DOCUMENT PASSWORD")
                ),
                contextlib.redirect_stdout(io.StringIO()) as output,
            ):
                self.assertEqual(citations.main(argv), 1)
            self.assertNotIn("PRIVATE", output.getvalue())
